# Numpy_Assignment_2::

# Question:1

### Convert a 1D array to a 2D array with 2 rows?

In [2]:
pip install numpy

     |████████████████████████████████| 14.5 MB 6.2 MB/s eta 0:00:01    |████▋                           | 2.1 MB 6.2 MB/s eta 0:00:02     |████████████████████████████    | 12.7 MB 6.2 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1)
print("----------------")
arr1.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]
----------------


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
a = np.arange(0,10).reshape(2,5)
b = np.ones((2,5),dtype=int).reshape(2,5)
print(a)
print(b)
print("----Solution-----")
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
----Solution-----


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
a = np.arange(0,10).reshape(2,5)
b = np.ones((2,5),dtype=int).reshape(2,5)
print(a)
print(b)
print("----Solution-----")
np.hstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
----Solution-----


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
a = np.array([0,1,2,3,4,5,6,7,8,9,]).reshape(5,2)
print(a)
print("----Solution-----")
np.ravel(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
----Solution-----


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
a = np.arange(0,15).reshape(5,3)
print(a)
print("----Solution-----")
a.reshape(1,15)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
----Solution-----


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [9]:
a = np.arange(0,15)
print(a)
print("----Solution-----")
a.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
----Solution-----


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [12]:
a = np.arange(4,29).reshape(5,5)
print(a)
print("----Solution-----")
np.sqrt(a)

[[ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]
 [24 25 26 27 28]]
----Solution-----


array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        , 4.12310563, 4.24264069],
       [4.35889894, 4.47213595, 4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262]])

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
a = np.random.randn(5,6)
print(a)
print("----Solution-----")
a.mean()

[[-0.89668007 -0.47707739  1.37322487  1.33950355  0.1616528   1.73001746]
 [-0.09424555  0.92535389  0.49342904 -0.2238324  -0.59773401 -0.67505741]
 [-1.03249232 -0.00791463 -0.74703126  0.15189526 -0.98140711 -0.07320787]
 [ 0.78444469 -0.47278292  1.56954971 -0.72991078  0.4886569  -2.05745583]
 [ 1.15197517  1.20193961  0.14431843  0.67121837  1.26865288 -0.22521333]]
----Solution-----


0.1387929904382372

## Question:9

### Find the standard deviation of the previous array in Q8?

In [14]:
print(a)
print("----Solution-----")
a.std()

[[-0.89668007 -0.47707739  1.37322487  1.33950355  0.1616528   1.73001746]
 [-0.09424555  0.92535389  0.49342904 -0.2238324  -0.59773401 -0.67505741]
 [-1.03249232 -0.00791463 -0.74703126  0.15189526 -0.98140711 -0.07320787]
 [ 0.78444469 -0.47278292  1.56954971 -0.72991078  0.4886569  -2.05745583]
 [ 1.15197517  1.20193961  0.14431843  0.67121837  1.26865288 -0.22521333]]
----Solution-----


0.9119690661922498

## Question:10

### Find the median of the previous array in Q8?

In [15]:
print(a)
print("----Solution-----")
np.median(a)

[[-0.89668007 -0.47707739  1.37322487  1.33950355  0.1616528   1.73001746]
 [-0.09424555  0.92535389  0.49342904 -0.2238324  -0.59773401 -0.67505741]
 [-1.03249232 -0.00791463 -0.74703126  0.15189526 -0.98140711 -0.07320787]
 [ 0.78444469 -0.47278292  1.56954971 -0.72991078  0.4886569  -2.05745583]
 [ 1.15197517  1.20193961  0.14431843  0.67121837  1.26865288 -0.22521333]]
----Solution-----


0.06820189688987617

## Question:11

### Find the transpose of the previous array in Q8?

In [16]:
print(a)
print("----Solution-----")
a.transpose()

[[-0.89668007 -0.47707739  1.37322487  1.33950355  0.1616528   1.73001746]
 [-0.09424555  0.92535389  0.49342904 -0.2238324  -0.59773401 -0.67505741]
 [-1.03249232 -0.00791463 -0.74703126  0.15189526 -0.98140711 -0.07320787]
 [ 0.78444469 -0.47278292  1.56954971 -0.72991078  0.4886569  -2.05745583]
 [ 1.15197517  1.20193961  0.14431843  0.67121837  1.26865288 -0.22521333]]
----Solution-----


array([[-0.89668007, -0.09424555, -1.03249232,  0.78444469,  1.15197517],
       [-0.47707739,  0.92535389, -0.00791463, -0.47278292,  1.20193961],
       [ 1.37322487,  0.49342904, -0.74703126,  1.56954971,  0.14431843],
       [ 1.33950355, -0.2238324 ,  0.15189526, -0.72991078,  0.67121837],
       [ 0.1616528 , -0.59773401, -0.98140711,  0.4886569 ,  1.26865288],
       [ 1.73001746, -0.67505741, -0.07320787, -2.05745583, -0.22521333]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [19]:
a = np.random.randn(4,4)
print(a)
print("----Solution-----")
a.diagonal()

[[ 1.03303498e+00  7.80054945e-01 -4.55117517e-02  8.14226691e-01]
 [ 1.63812755e+00 -2.11351372e+00  1.61613774e-01 -1.30021612e+00]
 [-4.65170148e-01  2.71211618e-01  7.92533164e-01  5.45194688e-01]
 [-1.68456592e-03  1.02944363e+00 -9.29315217e-02 -1.31715609e+00]]
----Solution-----


array([ 1.03303498, -2.11351372,  0.79253316, -1.31715609])

## Question:13

### Find the determinant of the previous array in Q12?

In [22]:
print(a)
print("----Solution-----")
np.linalg.det(a)

[[ 1.03303498e+00  7.80054945e-01 -4.55117517e-02  8.14226691e-01]
 [ 1.63812755e+00 -2.11351372e+00  1.61613774e-01 -1.30021612e+00]
 [-4.65170148e-01  2.71211618e-01  7.92533164e-01  5.45194688e-01]
 [-1.68456592e-03  1.02944363e+00 -9.29315217e-02 -1.31715609e+00]]
----Solution-----


5.932546032766012

## Question:14

### Find the 5th and 95th percentile of an array?

In [23]:
c = np.arange(100).reshape(20,5)
print(c)
print("----Solution of 5th percentile-----")
np.percentile (c, 5, axis=None, out=None)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
----Solution-----


4.95

In [24]:
c = np.arange(100).reshape(20,5)
print(c)
print("----Solution of 95th percentile-----")
np.percentile (c, 95, axis=None, out=None)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
----Solution of 95th percentile-----


94.05

## Question:15

### How to find if a given array has any null values?

In [25]:
a = np.array([120,50,5,0,25,68,34,0,80,0])
print(a)
print("----Solution-----")
np.where(a==0,"null",a)

[120  50   5   0  25  68  34   0  80   0]
----Solution-----


array(['120', '50', '5', 'null', '25', '68', '34', 'null', '80', 'null'],
      dtype='<U21')